version: '3.8'

services:
    app:
        image: wp-core-theme-components
        container_name: wp-core-theme-components
        build:
            context: .
        ports:
            - 80:80
        volumes:
            - .:/opt/wp-core-theme-components
            - ./web:/var/www/html